### ISSUE TITLE
enhancment request for documentation: how to set up custom graph legend

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#124]
here is how to add a legend to a graph:
(cant see it really here but align the lines one space over from the pipe)
custom: |
               COMMENT: \n
               COMMENT: 0 = Initializing ReplTask thread \n
               COMMENT: 1 = Replication setup script fired from this node\n
               COMMENT: 2 = Replication is good\n

![legend](https://cloud.githubusercontent.com/assets/1815352/10213196/ed3820ac-67d7-11e5-9de4-02cdd933ee0e.JPG)

**Comment by cluther** [comment]
There's also special support for comment graph points. Though this is only working in Zenoss 4, not in Zenoss 5 yet.

```yaml
graphs:
  Severity History:
    units: severity
    miny: 0
    maxy: 5

    graphpoints:
      Operability:
        dpName: equipmentPsu_operability
        format: "%2.0lf"

    comments:
      - "0 = Clear"
      - "1 = Debug"
      - "2 = Info"
      - "3 = Warning"
      - "4 = Error"
      - "5 = Critical"
```
